version: "3.9"
services:
  database:
    image: postgres:16-alpine
    container_name: database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./storage/init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7-alpine
    container_name: cache
    ports:
      - "${REDIS_PORT:-6384}:6379"
volumes:
  data-volume:
